// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBknCBeVN-4LXOnvn_gth1A8PQhNjRMtuw',
    appId: '1:607546424481:web:851c0679bc0ff781f244e0',
    messagingSenderId: '607546424481',
    projectId: 'loginapp-5b3ae',
    authDomain: 'loginapp-5b3ae.firebaseapp.com',
    storageBucket: 'loginapp-5b3ae.firebasestorage.app',
    measurementId: 'G-79KR1T4GN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3n3UWUqq9nZ7D_-Ikm7FS4IBhe8fDFwM',
    appId: '1:607546424481:android:e43e6965d9790544f244e0',
    messagingSenderId: '607546424481',
    projectId: 'loginapp-5b3ae',
    storageBucket: 'loginapp-5b3ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVkfRq8Q-SRFTcz5vjpXc8A4TnF7iiyxc',
    appId: '1:607546424481:ios:f68248ce8955d590f244e0',
    messagingSenderId: '607546424481',
    projectId: 'loginapp-5b3ae',
    storageBucket: 'loginapp-5b3ae.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVkfRq8Q-SRFTcz5vjpXc8A4TnF7iiyxc',
    appId: '1:607546424481:ios:f68248ce8955d590f244e0',
    messagingSenderId: '607546424481',
    projectId: 'loginapp-5b3ae',
    storageBucket: 'loginapp-5b3ae.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBknCBeVN-4LXOnvn_gth1A8PQhNjRMtuw',
    appId: '1:607546424481:web:d2035237d26be9e2f244e0',
    messagingSenderId: '607546424481',
    projectId: 'loginapp-5b3ae',
    authDomain: 'loginapp-5b3ae.firebaseapp.com',
    storageBucket: 'loginapp-5b3ae.firebasestorage.app',
    measurementId: 'G-NJ3GBEL1TX',
  );
}
